// Generated by gencpp from file usv_msgs/RangeBearing.msg
// DO NOT EDIT!


#ifndef USV_MSGS_MESSAGE_RANGEBEARING_H
#define USV_MSGS_MESSAGE_RANGEBEARING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace usv_msgs
{
template <class ContainerAllocator>
struct RangeBearing_
{
  typedef RangeBearing_<ContainerAllocator> Type;

  RangeBearing_()
    : header()
    , range(0.0)
    , bearing(0.0)
    , elevation(0.0)  {
    }
  RangeBearing_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , range(0.0)
    , bearing(0.0)
    , elevation(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _range_type;
  _range_type range;

   typedef float _bearing_type;
  _bearing_type bearing;

   typedef float _elevation_type;
  _elevation_type elevation;





  typedef boost::shared_ptr< ::usv_msgs::RangeBearing_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::usv_msgs::RangeBearing_<ContainerAllocator> const> ConstPtr;

}; // struct RangeBearing_

typedef ::usv_msgs::RangeBearing_<std::allocator<void> > RangeBearing;

typedef boost::shared_ptr< ::usv_msgs::RangeBearing > RangeBearingPtr;
typedef boost::shared_ptr< ::usv_msgs::RangeBearing const> RangeBearingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::usv_msgs::RangeBearing_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::usv_msgs::RangeBearing_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::usv_msgs::RangeBearing_<ContainerAllocator1> & lhs, const ::usv_msgs::RangeBearing_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.range == rhs.range &&
    lhs.bearing == rhs.bearing &&
    lhs.elevation == rhs.elevation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::usv_msgs::RangeBearing_<ContainerAllocator1> & lhs, const ::usv_msgs::RangeBearing_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace usv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::usv_msgs::RangeBearing_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::usv_msgs::RangeBearing_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usv_msgs::RangeBearing_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usv_msgs::RangeBearing_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usv_msgs::RangeBearing_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usv_msgs::RangeBearing_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::usv_msgs::RangeBearing_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d277afbbd042ab113d2e5714cad41ad";
  }

  static const char* value(const ::usv_msgs::RangeBearing_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d277afbbd042ab1ULL;
  static const uint64_t static_value2 = 0x13d2e5714cad41adULL;
};

template<class ContainerAllocator>
struct DataType< ::usv_msgs::RangeBearing_<ContainerAllocator> >
{
  static const char* value()
  {
    return "usv_msgs/RangeBearing";
  }

  static const char* value(const ::usv_msgs::RangeBearing_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::usv_msgs::RangeBearing_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"float32 range\n"
"float32 bearing\n"
"float32 elevation\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::usv_msgs::RangeBearing_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::usv_msgs::RangeBearing_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.range);
      stream.next(m.bearing);
      stream.next(m.elevation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RangeBearing_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::usv_msgs::RangeBearing_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::usv_msgs::RangeBearing_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "range: ";
    Printer<float>::stream(s, indent + "  ", v.range);
    s << indent << "bearing: ";
    Printer<float>::stream(s, indent + "  ", v.bearing);
    s << indent << "elevation: ";
    Printer<float>::stream(s, indent + "  ", v.elevation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // USV_MSGS_MESSAGE_RANGEBEARING_H
