// Auto-generated. Do not edit!

// (in-package pkg_nav.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class local_pathResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.runResult = null;
      this.result = null;
    }
    else {
      if (initObj.hasOwnProperty('runResult')) {
        this.runResult = initObj.runResult
      }
      else {
        this.runResult = 0;
      }
      if (initObj.hasOwnProperty('result')) {
        this.result = initObj.result
      }
      else {
        this.result = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type local_pathResult
    // Serialize message field [runResult]
    bufferOffset = _serializer.int8(obj.runResult, buffer, bufferOffset);
    // Serialize message field [result]
    bufferOffset = _serializer.int32(obj.result, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type local_pathResult
    let len;
    let data = new local_pathResult(null);
    // Deserialize message field [runResult]
    data.runResult = _deserializer.int8(buffer, bufferOffset);
    // Deserialize message field [result]
    data.result = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 5;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pkg_nav/local_pathResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '2bb32d147ef990e66003bb2d7c8e0b98';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    int8  runResult  # #  -1：处理失败  0 : 未处理     1：正在处理   2：处理完成  
    int32 result #test -cyb
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new local_pathResult(null);
    if (msg.runResult !== undefined) {
      resolved.runResult = msg.runResult;
    }
    else {
      resolved.runResult = 0
    }

    if (msg.result !== undefined) {
      resolved.result = msg.result;
    }
    else {
      resolved.result = 0
    }

    return resolved;
    }
};

module.exports = local_pathResult;
