// Auto-generated. Do not edit!

// (in-package pkg_nav.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class local_pathFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.percent_complete = null;
      this.runState = null;
      this.progress_bar = null;
    }
    else {
      if (initObj.hasOwnProperty('percent_complete')) {
        this.percent_complete = initObj.percent_complete
      }
      else {
        this.percent_complete = 0.0;
      }
      if (initObj.hasOwnProperty('runState')) {
        this.runState = initObj.runState
      }
      else {
        this.runState = 0;
      }
      if (initObj.hasOwnProperty('progress_bar')) {
        this.progress_bar = initObj.progress_bar
      }
      else {
        this.progress_bar = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type local_pathFeedback
    // Serialize message field [percent_complete]
    bufferOffset = _serializer.float64(obj.percent_complete, buffer, bufferOffset);
    // Serialize message field [runState]
    bufferOffset = _serializer.int8(obj.runState, buffer, bufferOffset);
    // Serialize message field [progress_bar]
    bufferOffset = _serializer.float64(obj.progress_bar, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type local_pathFeedback
    let len;
    let data = new local_pathFeedback(null);
    // Deserialize message field [percent_complete]
    data.percent_complete = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [runState]
    data.runState = _deserializer.int8(buffer, bufferOffset);
    // Deserialize message field [progress_bar]
    data.progress_bar = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 17;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pkg_nav/local_pathFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '70d94d6334a1aed97d89bf9a2b40a965';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a feedback message 
    float64 percent_complete  # [0-1]   处理进度 
    int8    runState  #  -1：处理失败  0 : 未处理     1：正在处理   2：处理完成   
    
    float64 progress_bar  #test -cyb
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new local_pathFeedback(null);
    if (msg.percent_complete !== undefined) {
      resolved.percent_complete = msg.percent_complete;
    }
    else {
      resolved.percent_complete = 0.0
    }

    if (msg.runState !== undefined) {
      resolved.runState = msg.runState;
    }
    else {
      resolved.runState = 0
    }

    if (msg.progress_bar !== undefined) {
      resolved.progress_bar = msg.progress_bar;
    }
    else {
      resolved.progress_bar = 0.0
    }

    return resolved;
    }
};

module.exports = local_pathFeedback;
