# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from pkg_nav/local_pathFeedback.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class local_pathFeedback(genpy.Message):
  _md5sum = "70d94d6334a1aed97d89bf9a2b40a965"
  _type = "pkg_nav/local_pathFeedback"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# Define a feedback message 
float64 percent_complete  # [0-1]   处理进度 
int8    runState  #  -1：处理失败  0 : 未处理     1：正在处理   2：处理完成   

float64 progress_bar  #test -cyb
"""
  __slots__ = ['percent_complete','runState','progress_bar']
  _slot_types = ['float64','int8','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       percent_complete,runState,progress_bar

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(local_pathFeedback, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.percent_complete is None:
        self.percent_complete = 0.
      if self.runState is None:
        self.runState = 0
      if self.progress_bar is None:
        self.progress_bar = 0.
    else:
      self.percent_complete = 0.
      self.runState = 0
      self.progress_bar = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_dbd().pack(_x.percent_complete, _x.runState, _x.progress_bar))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.percent_complete, _x.runState, _x.progress_bar,) = _get_struct_dbd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_dbd().pack(_x.percent_complete, _x.runState, _x.progress_bar))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.percent_complete, _x.runState, _x.progress_bar,) = _get_struct_dbd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_dbd = None
def _get_struct_dbd():
    global _struct_dbd
    if _struct_dbd is None:
        _struct_dbd = struct.Struct("<dbd")
    return _struct_dbd
