(cl:defpackage vrx_gazebo-srv
  (:use )
  (:export
   "BALLSHOOTER"
   "<BALLSHOOTER-REQUEST>"
   "BALLSHOOTER-REQUEST"
   "<BALLSHOOTER-RESPONSE>"
   "BALLSHOOTER-RESPONSE"
   "COLORSEQUENCE"
   "<COLORSEQUENCE-REQUEST>"
   "COLORSEQUENCE-REQUEST"
   "<COLORSEQUENCE-RESPONSE>"
   "COLORSEQUENCE-RESPONSE"
  ))

