// Generated by gencpp from file pkg_nav/global_pathFeedback.msg
// DO NOT EDIT!


#ifndef PKG_NAV_MESSAGE_GLOBAL_PATHFEEDBACK_H
#define PKG_NAV_MESSAGE_GLOBAL_PATHFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pkg_nav
{
template <class ContainerAllocator>
struct global_pathFeedback_
{
  typedef global_pathFeedback_<ContainerAllocator> Type;

  global_pathFeedback_()
    : percent_complete(0.0)
    , progress_bar(0.0)  {
    }
  global_pathFeedback_(const ContainerAllocator& _alloc)
    : percent_complete(0.0)
    , progress_bar(0.0)  {
  (void)_alloc;
    }



   typedef double _percent_complete_type;
  _percent_complete_type percent_complete;

   typedef double _progress_bar_type;
  _progress_bar_type progress_bar;





  typedef boost::shared_ptr< ::pkg_nav::global_pathFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg_nav::global_pathFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct global_pathFeedback_

typedef ::pkg_nav::global_pathFeedback_<std::allocator<void> > global_pathFeedback;

typedef boost::shared_ptr< ::pkg_nav::global_pathFeedback > global_pathFeedbackPtr;
typedef boost::shared_ptr< ::pkg_nav::global_pathFeedback const> global_pathFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg_nav::global_pathFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg_nav::global_pathFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pkg_nav::global_pathFeedback_<ContainerAllocator1> & lhs, const ::pkg_nav::global_pathFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.percent_complete == rhs.percent_complete &&
    lhs.progress_bar == rhs.progress_bar;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pkg_nav::global_pathFeedback_<ContainerAllocator1> & lhs, const ::pkg_nav::global_pathFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pkg_nav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pkg_nav::global_pathFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_nav::global_pathFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_nav::global_pathFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_nav::global_pathFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_nav::global_pathFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_nav::global_pathFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg_nav::global_pathFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4ae8417c8b17e91babe7a86363602f0d";
  }

  static const char* value(const ::pkg_nav::global_pathFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4ae8417c8b17e91bULL;
  static const uint64_t static_value2 = 0xabe7a86363602f0dULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg_nav::global_pathFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg_nav/global_pathFeedback";
  }

  static const char* value(const ::pkg_nav::global_pathFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg_nav::global_pathFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define a feedback message \n"
"float64 percent_complete  # [0-1]   处理进度 \n"
"float64 progress_bar  #test -cyb\n"
;
  }

  static const char* value(const ::pkg_nav::global_pathFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg_nav::global_pathFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percent_complete);
      stream.next(m.progress_bar);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct global_pathFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg_nav::global_pathFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg_nav::global_pathFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percent_complete: ";
    Printer<double>::stream(s, indent + "  ", v.percent_complete);
    s << indent << "progress_bar: ";
    Printer<double>::stream(s, indent + "  ", v.progress_bar);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG_NAV_MESSAGE_GLOBAL_PATHFEEDBACK_H
