// Generated by gencpp from file pkg_nav/global_path.msg
// DO NOT EDIT!


#ifndef PKG_NAV_MESSAGE_GLOBAL_PATH_H
#define PKG_NAV_MESSAGE_GLOBAL_PATH_H

#include <ros/service_traits.h>


#include <pkg_nav/global_pathRequest.h>
#include <pkg_nav/global_pathResponse.h>


namespace pkg_nav
{

struct global_path
{

typedef global_pathRequest Request;
typedef global_pathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct global_path
} // namespace pkg_nav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pkg_nav::global_path > {
  static const char* value()
  {
    return "ba39a456f802a4a81c4d35cdebddff8d";
  }

  static const char* value(const ::pkg_nav::global_path&) { return value(); }
};

template<>
struct DataType< ::pkg_nav::global_path > {
  static const char* value()
  {
    return "pkg_nav/global_path";
  }

  static const char* value(const ::pkg_nav::global_path&) { return value(); }
};


// service_traits::MD5Sum< ::pkg_nav::global_pathRequest> should match
// service_traits::MD5Sum< ::pkg_nav::global_path >
template<>
struct MD5Sum< ::pkg_nav::global_pathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pkg_nav::global_path >::value();
  }
  static const char* value(const ::pkg_nav::global_pathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg_nav::global_pathRequest> should match
// service_traits::DataType< ::pkg_nav::global_path >
template<>
struct DataType< ::pkg_nav::global_pathRequest>
{
  static const char* value()
  {
    return DataType< ::pkg_nav::global_path >::value();
  }
  static const char* value(const ::pkg_nav::global_pathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pkg_nav::global_pathResponse> should match
// service_traits::MD5Sum< ::pkg_nav::global_path >
template<>
struct MD5Sum< ::pkg_nav::global_pathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pkg_nav::global_path >::value();
  }
  static const char* value(const ::pkg_nav::global_pathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg_nav::global_pathResponse> should match
// service_traits::DataType< ::pkg_nav::global_path >
template<>
struct DataType< ::pkg_nav::global_pathResponse>
{
  static const char* value()
  {
    return DataType< ::pkg_nav::global_path >::value();
  }
  static const char* value(const ::pkg_nav::global_pathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PKG_NAV_MESSAGE_GLOBAL_PATH_H
