// Generated by gencpp from file pkg_nav/local_pathGoal.msg
// DO NOT EDIT!


#ifndef PKG_NAV_MESSAGE_LOCAL_PATHGOAL_H
#define PKG_NAV_MESSAGE_LOCAL_PATHGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/Path.h>

namespace pkg_nav
{
template <class ContainerAllocator>
struct local_pathGoal_
{
  typedef local_pathGoal_<ContainerAllocator> Type;

  local_pathGoal_()
    : local_path()
    , num(0)
    , runCommand(0)  {
    }
  local_pathGoal_(const ContainerAllocator& _alloc)
    : local_path(_alloc)
    , num(0)
    , runCommand(0)  {
  (void)_alloc;
    }



   typedef  ::nav_msgs::Path_<ContainerAllocator>  _local_path_type;
  _local_path_type local_path;

   typedef int32_t _num_type;
  _num_type num;

   typedef int32_t _runCommand_type;
  _runCommand_type runCommand;





  typedef boost::shared_ptr< ::pkg_nav::local_pathGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg_nav::local_pathGoal_<ContainerAllocator> const> ConstPtr;

}; // struct local_pathGoal_

typedef ::pkg_nav::local_pathGoal_<std::allocator<void> > local_pathGoal;

typedef boost::shared_ptr< ::pkg_nav::local_pathGoal > local_pathGoalPtr;
typedef boost::shared_ptr< ::pkg_nav::local_pathGoal const> local_pathGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg_nav::local_pathGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg_nav::local_pathGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pkg_nav::local_pathGoal_<ContainerAllocator1> & lhs, const ::pkg_nav::local_pathGoal_<ContainerAllocator2> & rhs)
{
  return lhs.local_path == rhs.local_path &&
    lhs.num == rhs.num &&
    lhs.runCommand == rhs.runCommand;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pkg_nav::local_pathGoal_<ContainerAllocator1> & lhs, const ::pkg_nav::local_pathGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pkg_nav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pkg_nav::local_pathGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_nav::local_pathGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_nav::local_pathGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_nav::local_pathGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_nav::local_pathGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_nav::local_pathGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg_nav::local_pathGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7452c78fbbd2c3f3a4cb422fb3e192fe";
  }

  static const char* value(const ::pkg_nav::local_pathGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7452c78fbbd2c3f3ULL;
  static const uint64_t static_value2 = 0xa4cb422fb3e192feULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg_nav::local_pathGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg_nav/local_pathGoal";
  }

  static const char* value(const ::pkg_nav::local_pathGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg_nav::local_pathGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"nav_msgs/Path local_path  \n"
"int32 num  #test -cyb\n"
"int32 runCommand\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::pkg_nav::local_pathGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg_nav::local_pathGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.local_path);
      stream.next(m.num);
      stream.next(m.runCommand);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct local_pathGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg_nav::local_pathGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg_nav::local_pathGoal_<ContainerAllocator>& v)
  {
    s << indent << "local_path: ";
    s << std::endl;
    Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, indent + "  ", v.local_path);
    s << indent << "num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num);
    s << indent << "runCommand: ";
    Printer<int32_t>::stream(s, indent + "  ", v.runCommand);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG_NAV_MESSAGE_LOCAL_PATHGOAL_H
