// Generated by gencpp from file vrx_gazebo/BallShooterResponse.msg
// DO NOT EDIT!


#ifndef VRX_GAZEBO_MESSAGE_BALLSHOOTERRESPONSE_H
#define VRX_GAZEBO_MESSAGE_BALLSHOOTERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vrx_gazebo
{
template <class ContainerAllocator>
struct BallShooterResponse_
{
  typedef BallShooterResponse_<ContainerAllocator> Type;

  BallShooterResponse_()
    : success(false)  {
    }
  BallShooterResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::vrx_gazebo::BallShooterResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrx_gazebo::BallShooterResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BallShooterResponse_

typedef ::vrx_gazebo::BallShooterResponse_<std::allocator<void> > BallShooterResponse;

typedef boost::shared_ptr< ::vrx_gazebo::BallShooterResponse > BallShooterResponsePtr;
typedef boost::shared_ptr< ::vrx_gazebo::BallShooterResponse const> BallShooterResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vrx_gazebo::BallShooterResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vrx_gazebo::BallShooterResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vrx_gazebo::BallShooterResponse_<ContainerAllocator1> & lhs, const ::vrx_gazebo::BallShooterResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vrx_gazebo::BallShooterResponse_<ContainerAllocator1> & lhs, const ::vrx_gazebo::BallShooterResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vrx_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vrx_gazebo::BallShooterResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vrx_gazebo::BallShooterResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrx_gazebo::BallShooterResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrx_gazebo::BallShooterResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrx_gazebo::BallShooterResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrx_gazebo::BallShooterResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vrx_gazebo::BallShooterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::vrx_gazebo::BallShooterResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::vrx_gazebo::BallShooterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vrx_gazebo/BallShooterResponse";
  }

  static const char* value(const ::vrx_gazebo::BallShooterResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vrx_gazebo::BallShooterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::vrx_gazebo::BallShooterResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vrx_gazebo::BallShooterResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BallShooterResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vrx_gazebo::BallShooterResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vrx_gazebo::BallShooterResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VRX_GAZEBO_MESSAGE_BALLSHOOTERRESPONSE_H
