// Generated by gencpp from file vrx_gazebo/Contact.msg
// DO NOT EDIT!


#ifndef VRX_GAZEBO_MESSAGE_CONTACT_H
#define VRX_GAZEBO_MESSAGE_CONTACT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace vrx_gazebo
{
template <class ContainerAllocator>
struct Contact_
{
  typedef Contact_<ContainerAllocator> Type;

  Contact_()
    : header()
    , collision1()
    , collision2()  {
    }
  Contact_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , collision1(_alloc)
    , collision2(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _collision1_type;
  _collision1_type collision1;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _collision2_type;
  _collision2_type collision2;





  typedef boost::shared_ptr< ::vrx_gazebo::Contact_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrx_gazebo::Contact_<ContainerAllocator> const> ConstPtr;

}; // struct Contact_

typedef ::vrx_gazebo::Contact_<std::allocator<void> > Contact;

typedef boost::shared_ptr< ::vrx_gazebo::Contact > ContactPtr;
typedef boost::shared_ptr< ::vrx_gazebo::Contact const> ContactConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vrx_gazebo::Contact_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vrx_gazebo::Contact_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vrx_gazebo::Contact_<ContainerAllocator1> & lhs, const ::vrx_gazebo::Contact_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.collision1 == rhs.collision1 &&
    lhs.collision2 == rhs.collision2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vrx_gazebo::Contact_<ContainerAllocator1> & lhs, const ::vrx_gazebo::Contact_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vrx_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vrx_gazebo::Contact_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vrx_gazebo::Contact_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrx_gazebo::Contact_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrx_gazebo::Contact_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrx_gazebo::Contact_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrx_gazebo::Contact_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vrx_gazebo::Contact_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc95c38568039a66bfb95d0e976561b9";
  }

  static const char* value(const ::vrx_gazebo::Contact_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc95c38568039a66ULL;
  static const uint64_t static_value2 = 0xbfb95d0e976561b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::vrx_gazebo::Contact_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vrx_gazebo/Contact";
  }

  static const char* value(const ::vrx_gazebo::Contact_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vrx_gazebo::Contact_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string collision1\n"
"string collision2\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::vrx_gazebo::Contact_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vrx_gazebo::Contact_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.collision1);
      stream.next(m.collision2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Contact_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vrx_gazebo::Contact_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vrx_gazebo::Contact_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "collision1: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.collision1);
    s << indent << "collision2: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.collision2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VRX_GAZEBO_MESSAGE_CONTACT_H
