; Auto-generated. Do not edit!


(cl:in-package pkg_nav-msg)


;//! \htmlinclude local_pathResult.msg.html

(cl:defclass <local_pathResult> (roslisp-msg-protocol:ros-message)
  ((runResult
    :reader runResult
    :initarg :runResult
    :type cl:fixnum
    :initform 0)
   (result
    :reader result
    :initarg :result
    :type cl:integer
    :initform 0))
)

(cl:defclass local_pathResult (<local_pathResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <local_pathResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'local_pathResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pkg_nav-msg:<local_pathResult> is deprecated: use pkg_nav-msg:local_pathResult instead.")))

(cl:ensure-generic-function 'runResult-val :lambda-list '(m))
(cl:defmethod runResult-val ((m <local_pathResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pkg_nav-msg:runResult-val is deprecated.  Use pkg_nav-msg:runResult instead.")
  (runResult m))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <local_pathResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pkg_nav-msg:result-val is deprecated.  Use pkg_nav-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <local_pathResult>) ostream)
  "Serializes a message object of type '<local_pathResult>"
  (cl:let* ((signed (cl:slot-value msg 'runResult)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 256) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    )
  (cl:let* ((signed (cl:slot-value msg 'result)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <local_pathResult>) istream)
  "Deserializes a message object of type '<local_pathResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'runResult) (cl:if (cl:< unsigned 128) unsigned (cl:- unsigned 256))))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'result) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<local_pathResult>)))
  "Returns string type for a message object of type '<local_pathResult>"
  "pkg_nav/local_pathResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'local_pathResult)))
  "Returns string type for a message object of type 'local_pathResult"
  "pkg_nav/local_pathResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<local_pathResult>)))
  "Returns md5sum for a message object of type '<local_pathResult>"
  "2bb32d147ef990e66003bb2d7c8e0b98")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'local_pathResult)))
  "Returns md5sum for a message object of type 'local_pathResult"
  "2bb32d147ef990e66003bb2d7c8e0b98")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<local_pathResult>)))
  "Returns full string definition for message of type '<local_pathResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%int8  runResult  # #  -1：处理失败  0 : 未处理     1：正在处理   2：处理完成  ~%int32 result #test -cyb~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'local_pathResult)))
  "Returns full string definition for message of type 'local_pathResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%int8  runResult  # #  -1：处理失败  0 : 未处理     1：正在处理   2：处理完成  ~%int32 result #test -cyb~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <local_pathResult>))
  (cl:+ 0
     1
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <local_pathResult>))
  "Converts a ROS message object to a list"
  (cl:list 'local_pathResult
    (cl:cons ':runResult (runResult msg))
    (cl:cons ':result (result msg))
))
