; Auto-generated. Do not edit!


(cl:in-package pkg_nav-msg)


;//! \htmlinclude local_pathGoal.msg.html

(cl:defclass <local_pathGoal> (roslisp-msg-protocol:ros-message)
  ((local_path
    :reader local_path
    :initarg :local_path
    :type nav_msgs-msg:Path
    :initform (cl:make-instance 'nav_msgs-msg:Path))
   (num
    :reader num
    :initarg :num
    :type cl:integer
    :initform 0)
   (runCommand
    :reader runCommand
    :initarg :runCommand
    :type cl:integer
    :initform 0))
)

(cl:defclass local_pathGoal (<local_pathGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <local_pathGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'local_pathGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pkg_nav-msg:<local_pathGoal> is deprecated: use pkg_nav-msg:local_pathGoal instead.")))

(cl:ensure-generic-function 'local_path-val :lambda-list '(m))
(cl:defmethod local_path-val ((m <local_pathGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pkg_nav-msg:local_path-val is deprecated.  Use pkg_nav-msg:local_path instead.")
  (local_path m))

(cl:ensure-generic-function 'num-val :lambda-list '(m))
(cl:defmethod num-val ((m <local_pathGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pkg_nav-msg:num-val is deprecated.  Use pkg_nav-msg:num instead.")
  (num m))

(cl:ensure-generic-function 'runCommand-val :lambda-list '(m))
(cl:defmethod runCommand-val ((m <local_pathGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pkg_nav-msg:runCommand-val is deprecated.  Use pkg_nav-msg:runCommand instead.")
  (runCommand m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <local_pathGoal>) ostream)
  "Serializes a message object of type '<local_pathGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'local_path) ostream)
  (cl:let* ((signed (cl:slot-value msg 'num)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
  (cl:let* ((signed (cl:slot-value msg 'runCommand)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <local_pathGoal>) istream)
  "Deserializes a message object of type '<local_pathGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'local_path) istream)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'num) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'runCommand) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<local_pathGoal>)))
  "Returns string type for a message object of type '<local_pathGoal>"
  "pkg_nav/local_pathGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'local_pathGoal)))
  "Returns string type for a message object of type 'local_pathGoal"
  "pkg_nav/local_pathGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<local_pathGoal>)))
  "Returns md5sum for a message object of type '<local_pathGoal>"
  "7452c78fbbd2c3f3a4cb422fb3e192fe")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'local_pathGoal)))
  "Returns md5sum for a message object of type 'local_pathGoal"
  "7452c78fbbd2c3f3a4cb422fb3e192fe")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<local_pathGoal>)))
  "Returns full string definition for message of type '<local_pathGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%nav_msgs/Path local_path  ~%int32 num  #test -cyb~%int32 runCommand~%~%~%~%================================================================================~%MSG: nav_msgs/Path~%#An array of poses that represents a Path for a robot to follow~%Header header~%geometry_msgs/PoseStamped[] poses~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'local_pathGoal)))
  "Returns full string definition for message of type 'local_pathGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%nav_msgs/Path local_path  ~%int32 num  #test -cyb~%int32 runCommand~%~%~%~%================================================================================~%MSG: nav_msgs/Path~%#An array of poses that represents a Path for a robot to follow~%Header header~%geometry_msgs/PoseStamped[] poses~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <local_pathGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'local_path))
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <local_pathGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'local_pathGoal
    (cl:cons ':local_path (local_path msg))
    (cl:cons ':num (num msg))
    (cl:cons ':runCommand (runCommand msg))
))
